
- hosts:  all
  become: yes
  tasks:

    - name: install fitness
      unarchive:
        src: https://github.com/fhoeben/hsac-fitnesse-fixtures/releases/download/2.11.6/hsac-fitnesse-fixtures-2.11.6-standalone.zip
        validate_certs: no
        remote: true
        mode: 755
        dest: /fitnesse


    - name: install plugins
      get_url:
          validate_certs: no
          url: "{{item}}"
          dest: /fitnesse/plugins/{{item |  urlsplit('path') }}
          mode: 755
      with_items:
        - https://github.com/six42/jdbcslim/releases/download/v1.0.1/jdbcslim.jar
        - https://sourceforge.net/projects/csvjdbc/files/CsvJdbc/1.0-18/csvjdbc-1.0-18.jar
        - https://maven.atlassian.com/3rdparty/com/oracle/ojdbc6/11.2.0.4.0-atlassian-hosted/ojdbc6-11.2.0.4.0-atlassian-hosted.jar
        - http://central.maven.org/maven2/com/github/dbfit/dbfit/3.2.0/dbfit-3.2.0.jar
        - http://central.maven.org/maven2/org/postgresql/postgresql/9.3-1101-jdbc41/postgresql-9.3-1101-jdbc41.jar
        - http://central.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
        - http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.40/mysql-connector-java-5.1.40.jar

    - name: JDBC Plugin Documentation
      shell:  wget "https://github.com/six42/jdbcslim/archive/v1.0.1.zip" && unzip v1.0.1.zip &&  mv jdbcslim-1.0.1/FitNesseRoot/PlugIns /fitnesse/FitNesseRoot/ && rm -fr v1.0.1.zip jdbcslim-1.0.1

    - name: Fix JDBC Documentation Installation wiki windows path by overwriting with the correct contents
      copy:
        dest: /fitnesse/FitNesseRoot/PlugIns/JdbcSlim/Installation/content.txt
        content:
